<?php
// $Id$

define('MIGRATE_DRUPAL_ACCESS_MIGRATE', 'migrate from drupal sites');
define('MIGRATE_DRUPAL_ACCESS_CONFIGURE', 'configure migration from drupal sites');

/**
 * @file
 * API and drush commands to support migration of data from external Drupal sites
 * into a Drupal installation.
 */

/**
 * Implements hook_permission().
 */
function migrate_drupal_permission() {
  return array(
    MIGRATE_DRUPAL_ACCESS_MIGRATE => array(
      'title' => t('Migrate external Drupal sites into Drupal'),
    ),
    MIGRATE_DRUPAL_ACCESS_CONFIGURE => array(
      'title' => t('Configure migration of external Drupal sites'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function migrate_drupal_menu() {
  $items = array();

  $items['admin/content/migrate_drupal'] = array(
    'title' => 'Drupal migration',
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
    'description' => 'Migrate external Drupal content into Drupal',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('migrate_drupal_import'),
    'access arguments' => array(MIGRATE_DRUPAL_ACCESS_MIGRATE),
    'file' => 'pages.import.inc',
    'weight' => 10,
  );
  $items['admin/content/migrate_drupal/import'] = array(
    'title' => 'Import',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/content/migrate_drupal/review'] = array(
    'title' => 'Review',
    'type' => MENU_LOCAL_TASK,
    'description' => 'Review and manage Drupal migrations',
    'page callback' => 'migrate_drupal_review',
    'access arguments' => array(MIGRATE_DRUPAL_ACCESS_MIGRATE),
    'file' => 'migrate_drupal.pages.inc',
    'weight' => 0,
  );
  $items['admin/content/migrate_drupal/configure'] = array(
    'title' => 'Configure',
    'type' => MENU_LOCAL_TASK,
    'description' => 'Configure external Drupal migration into Drupal',
    'page callback' => 'migrate_drupal_configure',
    'access arguments' => array(MIGRATE_DRUPAL_ACCESS_CONFIGURE),
    'file' => 'migrate_drupal.pages.inc',
    'weight' => 10,
  );

  return $items;
}

/*
 * Implementation of hook_migrate_api().
 */
function migrate_drupal_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

/**
 * Implementation of hook_mail().
 *
 * @param $key
 * @param $message
 * @param $params
 */
function migrate_drupal_mail($key, &$message, $params) {
  $data['user'] = $params['account'];
  $options['language'] = $message['language'];
  $variables = array();
  user_mail_tokens($variables, $data, $options);
  $variables['!output'] = $params['output'];
  $langcode = $message['language']->language;
  $subject = variable_get('migrate_drupal_notification_subject', '');
  $message['subject'] = t($subject, $variables, array('langcode' => $langcode));
  switch ($key) {
    case 'import_complete':
      $body = variable_get('migrate_drupal_notification_body', '');
      break;
    case 'import_failure':
      $body = variable_get('migrate_drupal_notification_failure_body', '');
      break;
  }
  $message['body'][] = t($body, $variables, array('langcode' => $langcode));
}

function migrate_drupal_site_class() {
  return variable_get('migrate_drupal_site_class', 'DrupalSite');
}

function migrate_drupal_site($endpoint, $token = NULL) {
  $site_class = migrate_drupal_site_class();
  return new $site_class($endpoint, $token);
}
